name: Build and deploy ASP.Net Core app to Azure Web App - fs1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fs1
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build the ASP.NET Core app
      - name: Build with dotnet
        run: dotnet build ./Server/Server.csproj --configuration Release

      # Publish the ASP.NET Core app
      - name: dotnet publish
        run: dotnet publish ./Server/Server.csproj -c Release -o ./publish

      # Build the Angular app
      - name: Build Angular
        run: |
          cd Client
          npm install
          npx ng build --configuration production
        shell: pwsh

      # Copy Angular build output to ASP.NET Core wwwroot
      - name: Copy Angular output to wwwroot
        run: |
          $angularOutputPath = 'Client/dist/client'
          $serverWwwrootPath = 'Server/wwwroot'
          New-Item -ItemType Directory -Force -Path $serverWwwrootPath
          Copy-Item -Path $angularOutputPath/* -Destination $serverWwwrootPath -Recurse -Force
        shell: pwsh

      # Upload the published ASP.NET Core app as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: net-app
          path: ./Server/wwwroot

      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1DA818086BFE4065AB06C6B15B75A45F }}
          package: './Server/wwwroot'





# name: Build and deploy ASP.Net Core app to Azure Web App - fs1

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '8.0.x' 

#       - name: Build with dotnet
#         run: dotnet build ./Server/Server.csproj --configuration Release

#       - name: dotnet publish
#         run: dotnet publish ./Server/Server.csproj -c Release -o ./publish

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: net-app
#           path: ./Server/bin/Debug/net6.0/publish/

#   deploy:
#     runs-on: windows-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: net-app

#       - name: List files in the directory
#         run: Get-ChildItem -Path "./" -Name
        

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'fs1'
#           slot-name: 'Production'
          # publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1DA818086BFE4065AB06C6B15B75A45F }}
#           package: net-app

          


